# Generated by Django 4.1.6 on 2023-02-08 14:17

from django.db import migrations, models
import django.db.models.deletion
import scanner.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255, unique=True, validators=[scanner.models.full_domain_validator], verbose_name='domain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'finished'), (2, 'ongoing'), (3, 'error')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain_name', models.CharField(max_length=255, verbose_name='subdomain_name')),
                ('result', models.TextField(verbose_name='result')),
                ('ip_address', models.GenericIPAddressField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.website')),
            ],
        ),
    ]
